[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
anyhow = "1.0.75"
bincode = "2.0.0-rc.3"
log = "0.4.20"
fern = "0.6.2"
humantime = "2.1.0"